# /etc/ipsec.conf — siteB-gw
# Site-to-Site IPsec VPN Configuration (StrongSwan)
# Generated: 2026-03-23

config setup
    charondebug="ike 2, knl 2, cfg 2"
    uniqueids=yes

conn %default
    ikelifetime=60m
    keylife=20m
    rekeymargin=3m
    keyingtries=1
    keyexchange=ikev2

conn site-to-site
    authby=secret
    left=10.10.99.2
    leftsubnet=10.10.20.0/24
    leftid=10.10.99.2
    right=10.10.99.1
    rightsubnet=10.10.10.0/24
    rightid=10.10.99.1
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256-modp2048!
    keyexchange=ikev2
    auto=start
    dpdaction=restart
    dpddelay=30s
    dpdtimeout=120s
